# Generated by Django 5.2.8 on 2025-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techer_name', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=20)),
                ('course_time', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
