# Generated by Django 5.2.6 on 2025-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiquest',
            old_name='techer_name',
            new_name='teacher_name',
        ),
    ]
